# Generated by Django 4.1.2 on 2022-10-25 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.TimeField(default=datetime.datetime(2022, 10, 25, 10, 22, 8, 350181, tzinfo=datetime.timezone.utc)),
        ),
    ]
