# Generated by Django 4.1.2 on 2022-10-27 04:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_alter_test_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.TimeField(default=datetime.datetime(2022, 10, 27, 4, 30, 59, 521526, tzinfo=datetime.timezone.utc)),
        ),
    ]
