# Generated by Django 4.1.2 on 2022-10-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_creator_name_alter_test_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
